version: 2.1

commands:
  run-npm-test:
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      # run tests!
      - run: npm test
jobs:
  node-v10:
    docker:
      - image: circleci/node:10@sha256:2add6e6e7406a384644f93ef43b5c56900d8aed3b44afc160f9a60bcec963ef8
    steps:
      - run-npm-test
  node-v12:
    docker:
      - image: circleci/node:12
    steps:
      - run-npm-test

workflows:
  multiple_builds:
    jobs:
      - node-v10
      - node-v12